--引入插件
require('plugins')
--基础配置
require('basic')
--快捷键
require('keybindings')
-- 主题颜色
require("colorscheme")
--tree插件配置
require("plugin-config.nvim-tree")
--bufferline插件
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
--require("plugin-config.nvim-treesitter")
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("plugin-config.indent-blankline")
require("lsp.null-ls")
